/**
 * 预置种子 / 示例数据（冷启动注入）。
 * 所有示例记录带 isSample:true，首页「清空示例」按钮调用 store.clearSamples() 仅删除这些记录。
 *
 * 内容准则：《个人投资体系总纲-人机共创融合版》（2026-08-21 版）
 * - 5 条核心底层信念（永久不变）→ 原则卡片 IS-2026-001~005
 * - 六大融合策略（分场景、带边界红线）→ 方法 M-2026-001~006
 * - 能力圈：科技 / 消费 / 医药 / 资源 / 红利 / 黄金 / 债券
 * - 个人硬约束：资金周期 2 年；最大回撤 ≤ 30%；中线+长线持仓；日均研究 0.5-1h
 */
import {
  createIS,
  createMethod,
  createTarget,
  createTrade,
  createReview,
  createObservation,
  createL1,
  createMaterial,
  createChangeLog,
  createMemo,
} from '../models/schemas'

export function seedData() {
  // ---------- 投资原则 IS（5 张，对应总纲 5 条核心底层信念） ----------
  const principles = [
    createIS({
      id: 'IS-2026-001',
      title: '风险优先，生存第一',
      module: '投资哲学',
      category: '宪法级',
      confidence: 95,
      validationPlan: '任何决策先问：最坏情况下是否会永久性亏损本金？若会，则放弃；最大回撤任何时候不超过 30%。',
      status: '已采纳',
      statement: '投资首要目标是规避永久性本金亏损，其次才是博取超额收益。所有盈利都是市场馈赠，活着才有复利机会。',
      source: '个人投资体系总纲（人机共创融合版）· 核心底层信念 ①',
      scope: '全部投资决策与风控底线，任何策略不得违背',
      relatedErrIds: ['ERR-2026-002', 'ERR-2026-004'],
      isConstitution: true,
      createdAt: '2026-08-21',
      updatedAt: '2026-08-21',
      isSample: true,
    }),
    createIS({
      id: 'IS-2026-002',
      title: '不懂不做，严守能力圈',
      module: '投资哲学',
      category: '宪法级',
      confidence: 93,
      validationPlan: '买入前必须能用三句话讲清商业模式、驱动因素与风险；能力圈外（非科技/消费/医药/资源/红利/黄金/债券）标的拒绝跟风。',
      status: '已采纳',
      statement: '不参与逻辑无法自洽、商业模式看不懂、驱动因素不清晰、风险不可预判的标的，拒绝跟风交易。',
      source: '个人投资体系总纲 · 核心底层信念 ②',
      scope: '标的研究与选股；能力圈覆盖：科技 / 消费 / 医药 / 资源 / 红利 / 黄金 / 债券',
      relatedErrIds: ['ERR-2026-003'],
      isConstitution: true,
      createdAt: '2026-08-21',
      updatedAt: '2026-08-21',
      isSample: true,
    }),
    createIS({
      id: 'IS-2026-003',
      title: '价格是情绪，价值是锚点',
      module: '估值纪律',
      category: '宪法级',
      confidence: 90,
      validationPlan: '买入必须留有安全边际；估值分位 > 80% 禁止追高；短期尊重趋势、长期坚守价值，不做纯价格博弈。',
      status: '已采纳',
      statement: '短期市场由资金、情绪、趋势驱动，长期由企业基本面、产业逻辑、现金流决定。尊重短期趋势，坚守长期价值。',
      source: '个人投资体系总纲 · 核心底层信念 ③（融合价值投资/趋势动量/反身性）',
      scope: '买入定价、持仓评估、止盈止损',
      relatedErrIds: ['ERR-2026-001'],
      isConstitution: true,
      createdAt: '2026-08-21',
      updatedAt: '2026-08-21',
      isSample: true,
    }),
    createIS({
      id: 'IS-2026-004',
      title: '超额收益来自认知差与逆向性',
      module: '收益来源',
      category: '可复用',
      confidence: 86,
      validationPlan: '不通过频繁交易、追涨杀跌博取收益；只在共识偏差、市场非理性、优质标的错杀时出手。',
      status: '已采纳',
      statement: '长期超额收益源于大众共识的偏差、市场短期非理性与优质标的错杀，而非频繁交易与追涨杀跌。',
      source: '个人投资体系总纲 · 核心底层信念 ④（融合逆向投资/成长价值）',
      scope: '策略选择与买入时机',
      relatedErrIds: ['ERR-2026-005'],
      isConstitution: false,
      createdAt: '2026-08-21',
      updatedAt: '2026-08-21',
      isSample: true,
    }),
    createIS({
      id: 'IS-2026-005',
      title: '周期轮回，资产轮动',
      module: '大类资产配置',
      category: '可复用',
      confidence: 84,
      validationPlan: '以宏观周期（复苏/过热/滞胀/衰退）为顶层调度，动态调整股票/债券/黄金/现金配置；以季度/半年为调仓周期，权益仓位不低于 30%。',
      status: '已采纳',
      statement: '经济与市场存在周期性规律，不同周期阶段适配不同大类资产；通过大类资产配置平滑组合波动，提升风险调整后收益。',
      source: '个人投资体系总纲 · 核心底层信念 ⑤（融合宏观大类资产配置哲学）',
      scope: '组合顶层调度与仓位总上限',
      relatedErrIds: ['ERR-2026-006'],
      isConstitution: false,
      createdAt: '2026-08-21',
      updatedAt: '2026-08-21',
      isSample: true,
    }),
  ]

  // ---------- L1 投资哲学（只读视图，宪法级细分） ----------
  const l1 = [
    createL1({
      id: 'L1-2026-001',
      category: '赚钱逻辑',
      title: '风险优先，活着才有复利',
      rule: '首要目标是规避永久性本金亏损，其次才是超额收益；盈利是市场馈赠。',
      boundary: '任何可能导致本金永久性损失的操作（加杠杆、押注超长周期价值回归）。',
      reason: '复利非线性：大幅回撤的修复时间远大于下跌时长，永久性亏损无法用时间抹平。',
      sourceIsId: 'IS-2026-001',
      isSample: true,
    }),
    createL1({
      id: 'L1-2026-002',
      category: '赚钱逻辑',
      title: '价值为锚，情绪为扰动',
      rule: '短期看资金与情绪，长期看基本面与现金流；尊重趋势但坚守价值。',
      boundary: '纯价格博弈、题材炒作、无基本面支撑的趋势追高。',
      reason: '价格围绕价值波动，安全边际可覆盖认知误差。',
      sourceIsId: 'IS-2026-003',
      isSample: true,
    }),
    createL1({
      id: 'L1-2026-003',
      category: '赚钱逻辑',
      title: '超额来自认知差与逆向',
      rule: '在共识偏差、市场非理性、优质标的错杀时出手，赚情绪修复与价值回归的钱。',
      boundary: '频繁交易、追涨杀跌、参与大众共识最狂热的方向。',
      reason: '频繁交易侵蚀收益，共识最拥挤处赔率最差。',
      sourceIsId: 'IS-2026-004',
      isSample: true,
    }),
    createL1({
      id: 'L1-2026-004',
      category: '赚钱逻辑',
      title: '周期轮回，资产轮动',
      rule: '以宏观周期为顶层调度，动态配置股票/债券/黄金/现金四类资产，平滑 2 年资金周期波动。',
      boundary: '不做月度级高频轮动、不用于个股择时。',
      reason: '不同周期阶段大类资产相对收益显著不同，配置可降低单一资产系统性风险。',
      sourceIsId: 'IS-2026-005',
      isSample: true,
    }),
    createL1({
      id: 'L1-2026-005',
      category: '不碰什么',
      title: '能力圈外不投',
      rule: '无法用三句话讲清商业模式、驱动因素与风险的标的，一律不投。',
      boundary: '能力圈（科技/消费/医药/资源/红利/黄金/债券）之外的陌生行业与复杂衍生品。',
      reason: '认知缺口是亏损的主要来源，不懂不做是成熟投资者的核心原则。',
      sourceIsId: 'IS-2026-002',
      isSample: true,
    }),
    createL1({
      id: 'L1-2026-006',
      category: '不碰什么',
      title: '不用杠杆，不赌超长周期',
      rule: '任何情形不使用融资融券、场外配资；不押注超过资金周期（2 年）的价值回归。',
      boundary: '杠杆头寸、3 年以上才可能兑现的逻辑。',
      reason: '杠杆会剥夺时间这个朋友；价值回归周期不可控，可能超出资金使用期限。',
      sourceIsId: 'IS-2026-001',
      isSample: true,
    }),
    createL1({
      id: 'L1-2026-007',
      category: '不碰什么',
      title: '不做纯技术面 / 纯题材交易',
      rule: '所有趋势操作必须绑定基本面合格标的；纯题材、无业绩支撑的赛道炒作一律不参与。',
      boundary: '震荡市中的假突破、高位鱼尾行情、情绪快速轮动题材。',
      reason: '纯技术趋势无基本面支撑时极易失效，题材炒作违背认知差原则。',
      sourceIsId: 'IS-2026-004',
      isSample: true,
    }),
    createL1({
      id: 'L1-2026-008',
      category: '风险底线',
      title: '最大回撤不超过 30%',
      rule: '组合回撤以 30% 为硬性上限，偏稳健，可接受适度波动，不可激进。',
      boundary: '任何导致回撤突破 30% 的加仓或风险暴露。',
      reason: '30% 回撤是个人可承受边界，风控规则为体系最高优先级。',
      sourceIsId: 'IS-2026-001',
      isSample: true,
    }),
    createL1({
      id: 'L1-2026-009',
      category: '风险底线',
      title: '仓位三层约束',
      rule: '单票 ≤ 组合 20%，单一行业 ≤ 40%，逆向投资单票 ≤ 5%。',
      boundary: '单一标的或行业集中度过高、逆向仓超出试错成本上限。',
      reason: '分散非系统性风险，防止黑天鹅对组合造成致命打击；逆向只做机动试错。',
      sourceIsId: 'IS-2026-001',
      isSample: true,
    }),
  ]

  // ---------- L2 投资方法（六大融合策略，对应总纲第四章） ----------
  const methods = [
    createMethod({
      id: 'M-2026-001',
      name: '宏观大类资产配置（顶层调度 · 权重 10%）',
      scenario: '组合顶层资产分配、经济周期拐点、政策转向期、系统性风险上升阶段。',
      assumptions: '经济运行存在复苏/过热/滞胀/衰退周期规律；不同周期大类资产相对收益显著不同。',
      steps: [
        '判断当前周期阶段（复苏/过热/滞胀/衰退）与流动性环境',
        '动态调整股票/债券/黄金/现金四大类资产配置比例',
        '周期向上提升权益仓位；周期向下增配债券与现金；风险事件增配黄金对冲',
        '以季度/半年为调仓周期，大类配置决定各策略总仓位上限',
        '权益资产最低仓位不低于 30%，避免完全踏空牛市',
      ],
      limitations: '宏观周期判断难度高，拐点极易误判；不用于个股择时，不作为收益增强核心手段。',
      status: '启用',
      relatedIsIds: ['IS-2026-005'],
      version: 'v1.0',
      isSample: true,
    }),
    createMethod({
      id: 'M-2026-002',
      name: '价值投资策略（底盘基石 · 权重 50%）',
      scenario: '核心持仓配置、震荡市、熊市底部、成熟期优质标的布局。',
      assumptions: '企业存在可测算的内在价值；价格长期向内在价值回归；安全边际可覆盖认知误差。',
      steps: [
        '以企业内在价值为锚，优选商业模式稳定、现金流扎实、ROE 持续稳健的标的',
        '严格坚守安全边际，仅在价格显著低于合理价值区间时分批买入',
        '连续两个季度核心盈利指标下滑且无复苏迹象时，立即重估内在价值，不硬扛价值陷阱',
        '估值回归至合理区间后，不再按价值逻辑加仓',
      ],
      limitations: '价值回归周期不可控，可能超出资金使用期限；需警惕基本面恶化的价值陷阱。',
      status: '启用',
      relatedIsIds: ['IS-2026-001', 'IS-2026-003'],
      version: 'v1.0',
      isSample: true,
    }),
    createMethod({
      id: 'M-2026-003',
      name: 'GARP 合理成长策略（收益主力 · 权重 30%）',
      scenario: '景气上行行业、结构性牛市、业绩确定性强的成长标的。',
      assumptions: '盈利增速是中期股价核心驱动；行业景气与企业增速具备 1-3 年持续性。',
      steps: [
        '以「业绩增速匹配估值水平」为核心标准选股',
        '精选行业渗透率提升、公司份额持续扩张的标的',
        '以产业趋势与政策导向为核心判断依据，财报与估值作验证辅助',
        'PE/PEG 显著高于行业中枢与自身历史分位时，停止加仓',
        '行业景气见顶或增速不及预期时，立即终止成长逻辑，切换价值评估或止盈离场',
      ],
      limitations: '对景气拐点判断要求极高；增速不及预期易遭遇「估值+业绩」双杀；避免将短期景气错判为长期能力。',
      status: '启用',
      relatedIsIds: ['IS-2026-003', 'IS-2026-004'],
      version: 'v1.0',
      isSample: true,
    }),
    createMethod({
      id: 'M-2026-004',
      name: '轻量化趋势策略（择时辅助 · 辅助工具）',
      scenario: '单边趋势行情、板块资金共振、右侧修复阶段。',
      assumptions: '资金与情绪具备惯性；趋势形成后短期不会立即反转；价格信号领先于基本面共识扩散。',
      steps: [
        '仅作为入场与仓位管理工具，不独立选股',
        '在基本面达标前提下，趋势确立时加仓提升资金效率',
        '趋势破位时减仓止盈，规避回撤',
        '震荡市自动停用趋势规则，避免频繁止损',
        '绝不追高鱼尾行情',
      ],
      limitations: '震荡市反复假突破，止损成本高；存在滞后性，无法精准捕捉拐点；纯技术趋势无基本面支撑时极易失效。',
      status: '启用',
      relatedIsIds: ['IS-2026-003', 'IS-2026-004'],
      version: 'v1.0',
      isSample: true,
    }),
    createMethod({
      id: 'M-2026-005',
      name: '逆向投资策略（机动超额 · 辅助工具）',
      scenario: '市场极端悲观、优质标的短期非致命利空、行业系统性情绪错杀。',
      assumptions: '市场情绪会周期性极端偏离基本面；短期非致命利空不改变企业长期内在价值。',
      steps: [
        '确认企业基本面未受损、利空为短期性',
        '分批左侧布局，赚取情绪修复与价值回归双重收益',
        '下跌趋势未企稳前不一次性满仓',
        '逆向仓位单票不超过总仓位的 5%，严格控制试错成本',
        '不抄底基本面永久恶化、被技术/政策颠覆的标的',
      ],
      limitations: '左侧抄底容易过早，逆势持仓心理压力大；难以精准区分「短期错杀」与「基本面永久恶化」。',
      status: '待验证',
      relatedIsIds: ['IS-2026-004'],
      version: 'v1.0',
      isSample: true,
    }),
    createMethod({
      id: 'M-2026-006',
      name: '防御型风控策略（全程兜底 · 最高优先级）',
      scenario: '全市场环境、所有持仓与交易动作。',
      assumptions: '复利非线性：大幅回撤的修复时长远大于下跌时长；永久性亏损无法通过时间抹平。',
      steps: [
        '仓位上限约束：组合总仓位与单票/行业集中度不超硬规则',
        '集中度约束：单票 ≤ 20%，单一行业 ≤ 40%，逆向单票 ≤ 5%',
        '止损止盈规则：跌破防守线按计划减仓，不因侥幸拖延',
        '不因市场狂热、短期踏空放松风控标准',
        '风控规则为体系最高优先级，任何策略均不得突破',
      ],
      limitations: '牛市中容易偏保守，阶段性跑输激进体系，牺牲部分上行弹性——此为体系有意为之。',
      status: '启用',
      relatedIsIds: ['IS-2026-001'],
      version: 'v1.0',
      isSample: true,
    }),
  ]

  // ---------- L3 标的研究（能力圈内示例：消费/科技 + 大类资产） ----------
  const targets = [
    createTarget({
      id: 'T-02097',
      name: '蜜雪集团',
      code: '02097.HK',
      currency: 'HKD',
      businessModel: '以极高性价比现制饮品为核心的供应链平台，靠加盟费、设备与食材销售赚钱，而非单杯毛利。',
      moat: '极致供应链效率 + 规模采购成本优势 + 下沉市场密度壁垒，品牌认知深入低线城镇。',
      keyFinancials: { currentPrice: 158.4, pe: 28, roe: 27.4, marketCap: '¥1560亿' },
      riskPoints: [
        '国内门店密度接近天花板，同店增长放缓',
        '食安与加盟商管理风险，单店事件易放大',
        '出海尚处投入期，东南亚盈利模型未完全跑通',
        '若增速不及预期，GARP 逻辑需切换至价值评估',
      ],
      valuationRange: { currentPercentile: 32, tiers: ['极冷', '冷', '中', '热', '极热'] },
      trackingPoints: ['月度开店数与新店回本周期', '东南亚单店 UE 模型', '原材料成本波动'],
      relatedIsIds: ['IS-2026-002', 'IS-2026-003'],
      relatedErrIds: ['ERR-2026-001'],
      stage: '深度',
      isSample: true,
    }),
    createTarget({
      id: 'T-06055',
      name: '中烟香港',
      code: '06055.HK',
      currency: 'HKD',
      businessModel: '独家运营卷烟及其他烟草制品的免税及批发贸易，牌照稀缺，现金流稳健。',
      moat: '牌照壁垒 + 烟草专营属性，需求刚性，具备红利属性。',
      keyFinancials: { currentPrice: 19.2, pe: 16, roe: 18.6, marketCap: '¥420亿' },
      riskPoints: ['政策与控烟风险', '免税渠道受旅游复苏波动', '品类单一'],
      valuationRange: { currentPercentile: 45, tiers: ['极冷', '冷', '中', '热', '极热'] },
      trackingPoints: ['免税客流恢复节奏', '新品引入进度', '分红率变化'],
      relatedIsIds: ['IS-2026-002'],
      relatedErrIds: [],
      stage: '研究中',
      isSample: true,
    }),
    createTarget({
      id: 'T-00700',
      name: '腾讯控股',
      code: '00700.HK',
      currency: 'HKD',
      businessModel: '社交+游戏+广告+金融科技+云的多引擎平台型公司，强网络效应。',
      moat: '微信社交网络效应 + 内容生态 + 资本与数据壁垒。',
      keyFinancials: { currentPrice: 368.0, pe: 19, roe: 21.2, marketCap: '¥3.4万亿' },
      riskPoints: ['监管与版号节奏', '游戏增长放缓', '宏观广告景气度'],
      valuationRange: { currentPercentile: 38, tiers: ['极冷', '冷', '中', '热', '极热'] },
      trackingPoints: ['视频号商业化', '游戏 pipeline', '回购节奏'],
      relatedIsIds: ['IS-2026-002'],
      relatedErrIds: [],
      stage: '跟踪中',
      isSample: true,
    }),
    createTarget({
      id: 'T-518880',
      name: '黄金 ETF',
      code: '518880.SH',
      currency: 'CNY',
      businessModel: '跟踪上海金交所黄金现货价格的 ETF，用于大类资产配置中的避险对冲。',
      moat: '流动性好的黄金现货工具，用于风险事件对冲与滞胀期配置。',
      keyFinancials: { currentPrice: 5.62, pe: null, roe: null, marketCap: '¥280亿' },
      riskPoints: ['实际利率上行压制金价', '美元走强', '高位波动'],
      valuationRange: { currentPercentile: null, tiers: ['极冷', '冷', '中', '热', '极热'] },
      trackingPoints: ['实际利率与美元指数', '央行购金节奏', '地缘风险溢价'],
      relatedIsIds: ['IS-2026-005'],
      relatedErrIds: [],
      stage: '研究中',
      isSample: true,
    }),
    createTarget({
      id: 'T-510880',
      name: '红利 ETF',
      code: '510880.SH',
      currency: 'CNY',
      businessModel: '跟踪上证红利指数的 ETF，聚焦高股息标的，用于滞胀期防御与现金流配置。',
      moat: '高股息低估值特征，在滞胀与熊市底部阶段具备防御属性。',
      keyFinancials: { currentPrice: 3.41, pe: 7.8, roe: null, marketCap: '¥190亿' },
      riskPoints: ['周期股占比高，盈利波动', '风格切换时跑输成长', '股息率受价格影响'],
      valuationRange: { currentPercentile: null, tiers: ['极冷', '冷', '中', '热', '极热'] },
      trackingPoints: ['股息率与无风险利率利差', '成分股盈利质量', '市场风格切换'],
      relatedIsIds: ['IS-2026-005'],
      relatedErrIds: [],
      stage: '研究中',
      isSample: true,
    }),
  ]

  // ---------- L4 交易日志（仅人工录入） ----------
  const trades = [
    createTrade({
      id: 'TR-001',
      date: '2026-08-05',
      targetId: 'T-02097',
      targetName: '蜜雪集团',
      direction: '做多',
      quantity: 1000,
      price: 148.2,
      currency: 'HKD',
      amount: 148200,
      industry: '餐饮连锁',
      memoId: 'MEMO-2026-0023',
      status: '已平仓',
      profit: 18600,
      decisionContext: {
        marketEnvironment: '消费板块估值修复，港股情绪回暖',
        valuation: 'PE 分位约 30%，处于冷区，安全边际充足',
        mentality: '计划内建仓（GARP+价值），无追涨',
        expectedReturn: '一年内 20%-30%',
        stopLoss: '跌破 130 减仓',
      },
      isSample: true,
    }),
    createTrade({
      id: 'TR-002',
      date: '2026-08-08',
      targetId: 'T-06055',
      targetName: '中烟香港',
      direction: '做多',
      quantity: 500,
      price: 18.5,
      currency: 'HKD',
      amount: 9250,
      industry: '烟草',
      memoId: '',
      status: '已归档',
      decisionContext: {
        marketEnvironment: '免税复苏预期',
        valuation: 'PE 16 倍，中性，红利属性',
        mentality: '小仓位试探（红利防御配置）',
        expectedReturn: '15%',
        stopLoss: '17 以下观察',
      },
      isSample: true,
    }),
    createTrade({
      id: 'TR-003',
      date: '2026-08-11',
      targetId: 'T-00700',
      targetName: '腾讯控股',
      direction: '做多',
      quantity: 200,
      price: 365.0,
      currency: 'HKD',
      amount: 73000,
      industry: '互联网',
      memoId: '',
      status: '已归档',
      decisionContext: {
        marketEnvironment: '平台经济监管缓和',
        valuation: 'PE 19 倍，历史中低位',
        mentality: '分批建仓（GARP 候选）',
        expectedReturn: '长持 25%+',
        stopLoss: '330 防守线',
      },
      isSample: true,
    }),
    createTrade({
      id: 'TR-004',
      date: '2026-08-14',
      targetId: '',
      targetName: '长桥证券某美股 NVDA',
      direction: '做多',
      quantity: 10,
      price: 120.0,
      currency: 'USD',
      amount: 1200,
      industry: '海外科技',
      memoId: '',
      status: '边界外·待核',
      isOutOfBoundary: true,
      decisionContext: {
        marketEnvironment: '美股 AI 行情（能力圈之外）',
        valuation: '未做能力圈评估',
        mentality: '临时起意，未经备忘录',
        expectedReturn: '不确定',
        stopLoss: '未设',
      },
      isSample: true,
    }),
    createTrade({
      id: 'TR-005',
      date: '2026-08-18',
      targetId: 'T-02097',
      targetName: '蜜雪集团',
      direction: '做多',
      quantity: 500,
      price: 152.0,
      currency: 'HKD',
      amount: 76000,
      industry: '餐饮连锁',
      memoId: 'MEMO-2026-0023',
      status: '已平仓',
      profit: 3200,
      decisionContext: {
        marketEnvironment: '中期财报超预期',
        valuation: 'PE 分位 32%，仍在冷区',
        mentality: '加码符合计划',
        expectedReturn: '20%',
        stopLoss: '140 防守',
      },
      isSample: true,
    }),
    createTrade({
      id: 'TR-006',
      date: '2026-08-20',
      targetId: 'T-518880',
      targetName: '黄金 ETF',
      direction: '做多',
      quantity: 20000,
      price: 5.62,
      currency: 'CNY',
      amount: 112400,
      industry: '黄金',
      memoId: '',
      status: '已归档',
      decisionContext: {
        marketEnvironment: '宏观不确定性与避险需求上升',
        valuation: '实际利率下行预期',
        mentality: '大类资产配置：黄金对冲仓（顶层调度）',
        expectedReturn: '对冲组合波动',
        stopLoss: '按大类配置比例调仓',
      },
      isSample: true,
    }),
  ]

  // ---------- L5 复盘与错误 ----------
  const reviews = [
    createReview({
      id: 'RV-001',
      type: '错误清单',
      errId: 'ERR-2026-001',
      category: '认知',
      title: '追高忽略估值',
      description: '在估值分位 > 80% 时仍因情绪追高买入，违背「价格是情绪，价值是锚点」，后续回撤显著。',
      relatedIsIds: ['IS-2026-003'],
      relatedTradeIds: [],
      reviewRecords: [
        { date: '2026-03-15', content: '首次在热门赛道高位追入', result: '短期浮亏 12%' },
        { date: '2026-05-20', content: '复盘确认是估值纪律缺失', result: '补充安全边际规则' },
        { date: '2026-08-01', content: '蜜雪建仓严格按分位执行', result: '未再犯，浮盈' },
      ],
      status: '已验证',
      isSample: true,
    }),
    createReview({
      id: 'RV-002',
      type: '错误清单',
      errId: 'ERR-2026-002',
      category: '心态',
      title: '止损犹豫',
      description: '亏损仓位因侥幸心理拖延止损，小亏拖成大亏，违背「风险优先，生存第一」。',
      relatedIsIds: ['IS-2026-001'],
      relatedTradeIds: [],
      reviewRecords: [{ date: '2026-04-10', content: '记录一次拖延止损案例', result: '待改进' }],
      status: '待验证',
      isSample: true,
    }),
    createReview({
      id: 'RV-003',
      type: '错误清单',
      errId: 'ERR-2026-003',
      category: '认知',
      title: '轻信小道消息',
      description: '依据未经证实的群聊消息买入，缺乏独立验证，违背「不懂不做，严守能力圈」。',
      relatedIsIds: ['IS-2026-002'],
      relatedTradeIds: [],
      reviewRecords: [{ date: '2026-02-28', content: '因消息买入后证伪', result: '小额止损' }],
      status: '已验证',
      isSample: true,
    }),
    createReview({
      id: 'RV-004',
      type: '错误清单',
      errId: 'ERR-2026-004',
      category: '执行',
      title: '仓位过重',
      description: '单票一度超过 20% 上限，行业集中度过高，波动放大，触发防御风控三层约束。',
      relatedIsIds: ['IS-2026-001'],
      relatedTradeIds: [],
      reviewRecords: [{ date: '2026-06-12', content: '触发硬规则预警', result: '已减仓至合规' }],
      status: '已验证',
      isSample: true,
    }),
    createReview({
      id: 'RV-005',
      type: '错误清单',
      errId: 'ERR-2026-005',
      category: '心态',
      title: '频繁交易',
      description: '过度交易侵蚀收益，增加摩擦成本与决策噪音，违背「超额收益来自认知差与逆向性」。',
      relatedIsIds: ['IS-2026-004'],
      relatedTradeIds: [],
      reviewRecords: [{ date: '2026-07-05', content: '统计月度换手率偏高', result: '设交易频率上限' }],
      status: '待验证',
      isSample: true,
    }),
    createReview({
      id: 'RV-006',
      type: '错误清单',
      errId: 'ERR-2026-006',
      category: '认知',
      title: '忽略宏观周期',
      description: '只看个股忽略利率与流动性宏观背景，择时被动，违背「周期轮回，资产轮动」。',
      relatedIsIds: ['IS-2026-005'],
      relatedTradeIds: [],
      reviewRecords: [{ date: '2026-08-02', content: '纳入宏观周期 Checklist', result: '待验证' }],
      status: '待验证',
      isSample: true,
    }),
    createReview({
      id: 'RV-101',
      type: '交易复盘',
      title: '蜜雪集团建仓复盘',
      description: '分两笔建仓，严格按估值分位与安全边际执行（GARP+价值双逻辑验证），结果符合预期。',
      relatedIsIds: ['IS-2026-003'],
      relatedTradeIds: ['TR-001', 'TR-005'],
      reviewRecords: [],
      status: '已验证',
      isSample: true,
    }),
  ]

  // ---------- L6 观察灵感 ----------
  const observations = [
    createObservation({
      id: 'OB-001',
      title: '蜜雪冰城东南亚首店落地雅加达',
      source: '突发新闻',
      sourceType: '突发',
      summary: '东南亚扩张迈出实质一步，验证出海叙事，需跟踪单店 UE 模型。',
      status: '待归档',
      relatedTargetIds: ['T-02097'],
      relatedMethodIds: ['M-2026-003'],
      relatedErrIds: [],
      createdAt: '2026-08-19',
      isSample: true,
    }),
    createObservation({
      id: 'OB-002',
      title: '现制饮品行业集中度加速提升',
      source: '行业研报',
      sourceType: '研报',
      summary: '头部品牌份额持续扩大，中小品牌出清，利好龙头供应链平台（GARP 景气验证）。',
      status: '待归档',
      relatedTargetIds: ['T-02097'],
      relatedMethodIds: ['M-2026-003'],
      relatedErrIds: [],
      createdAt: '2026-08-18',
      isSample: true,
    }),
    createObservation({
      id: 'OB-003',
      title: '消费降级下平价连锁的逆周期韧性',
      source: '投资公众号',
      sourceType: '公众号',
      summary: '低价高频刚需品类在经济弱周期中更具韧性，可作为价值防御配置思路。',
      status: '待归档',
      relatedTargetIds: ['T-02097'],
      relatedMethodIds: ['M-2026-002'],
      relatedErrIds: [],
      createdAt: '2026-08-17',
      isSample: true,
    }),
    createObservation({
      id: 'OB-004',
      title: '宏观周期观察：当前处于什么阶段？',
      source: '宏观数据',
      sourceType: '研报',
      summary: '待判断当前周期（复苏/过热/滞胀/衰退）与流动性环境，作为大类资产配置的顶层输入。',
      status: '待归档',
      relatedTargetIds: [],
      relatedMethodIds: ['M-2026-001'],
      relatedErrIds: ['ERR-2026-006'],
      createdAt: '2026-08-16',
      isSample: true,
    }),
    createObservation({
      id: 'OB-005',
      title: '用估值分位做仓位梯度',
      source: '自我灵感',
      sourceType: '灵感',
      summary: '分位越低买得越重，分位越高买得越轻，将安全边际转化为仓位函数（价值策略落地）。',
      status: '已归档',
      relatedTargetIds: [],
      relatedMethodIds: ['M-2026-002'],
      relatedErrIds: [],
      createdAt: '2026-08-10',
      isSample: true,
    }),
    createObservation({
      id: 'OB-006',
      title: '瑞幸财报超预期，验证平价咖啡需求',
      source: '财报新闻',
      sourceType: '新闻',
      summary: '同赛道可比公司数据向好，间接支撑蜜雪需求侧判断。',
      status: '已归档',
      relatedTargetIds: ['T-02097'],
      relatedMethodIds: [],
      relatedErrIds: [],
      createdAt: '2026-08-09',
      isSample: true,
    }),
  ]

  // ---------- 10. 投资备忘录 ----------
  const memos = [
    createMemo({
      id: 'MEMO-2026-0023',
      date: '2026-08-04',
      targetId: 'T-02097',
      targetName: '蜜雪集团',
      direction: '拟买',
      logic: '供应链平台型生意，规模与效率壁垒清晰；GARP 视角下增速匹配估值，价值视角下 PE 分位处冷区，双逻辑验证。',
      expectedReturn: '20%-30% / 一年',
      timeFrame: '12 个月',
      catalyst: '中期财报兑现开店与利润增长',
      risk: '国内密度见顶、出海盈利未证、食安事件；若增速不及预期需切换价值评估。',
      redTeamChallenge: '若出海模型跑不通、国内同店转负，则 GARP 成长叙事破裂，应推迟建仓；若市场已充分定价，安全边际消失，亦放弃。',
      exitConditions: 'PE 分位 > 80% 或基本面逻辑被破坏时退出。',
      confidence: 78,
      isIds: ['IS-2026-001', 'IS-2026-002', 'IS-2026-003'],
      errIds: ['ERR-2026-001'],
      status: '已决策',
      gateChecks: [true, true, true, true, true],
      decisionHistory: [
        { at: '2026-08-04', action: '创建', note: '七要素完整，引用 IS-2026-001/002/003 与 ERR-2026-001' },
        { at: '2026-08-05', action: '决策通过', note: '5 步闸门全通过，信心 78%' },
        { at: '2026-08-05', action: '执行建仓', note: '首笔 1000 股 @148.2' },
      ],
      isSample: true,
    }),
    createMemo({
      id: 'MEMO-2026-0024',
      date: '2026-08-21',
      targetId: 'T-00700',
      targetName: '腾讯控股',
      direction: '拟买',
      logic: '平台生态稳健，估值处历史中低位，回购提供安全垫（GARP 候选，增速匹配估值）。',
      expectedReturn: '25% / 两年',
      timeFrame: '24 个月',
      catalyst: '视频号商业化加速',
      risk: '监管与游戏 pipeline 不及预期。',
      redTeamChallenge: '',
      exitConditions: '',
      confidence: 52,
      isIds: [], // 故意缺失引用，用于演示闸门阻塞
      errIds: [],
      status: '草稿',
      gateChecks: [true, true, false, false, false],
      decisionHistory: [{ at: '2026-08-21', action: '创建', note: '待补齐红队挑战与原则引用' }],
      isSample: true,
    }),
  ]

  // ---------- 8. 资料-卡片索引 ----------
  const materials = [
    createMaterial({
      id: 'MT-001',
      materialTitle: '蜜雪集团 中期财报点评',
      materialUrl: '',
      isIds: ['IS-2026-003'],
      methodIds: ['M-2026-003'],
      targetIds: ['T-02097'],
      createdAt: '2026-08-05',
      isSample: true,
    }),
  ]

  // ---------- 9. 体系变更日志 ----------
  const logs = [
    createChangeLog({
      id: 'CL-001',
      type: '+',
      description: '植入《个人投资体系总纲-人机共创融合版》v2.0：5 条核心底层信念（IS-2026-001~005）与六大融合策略（M-2026-001~006）。',
      version: 'v2.0',
      createdAt: '2026-08-21',
      isSample: true,
    }),
    createChangeLog({
      id: 'CL-002',
      type: '~',
      description: '能力圈边界定义：科技 / 消费 / 医药 / 资源 / 红利 / 黄金 / 债券；新增黄金 ETF 与红利 ETF 大类资产观察标的。',
      version: 'v2.0',
      createdAt: '2026-08-21',
      isSample: true,
    }),
  ]

  // ---------- 11. 首页看板状态（市场时钟 / 资产吸引力 / 本月策略） ----------
  const todayStr = new Date().toISOString().slice(0, 10)
  const dashboard = {
    marketClock: {
      // 默认定位依据（2026-08，国家统计局 2026-08-17 发布）：CPI +0.9%（近通缩）、PPI +1.8%（温和回正）、
      // 规上工业增加值 +5.3%、社零 +2.6%（内需偏弱）、固投 -6.7%（地产拖累）、PMI 在 50 荣枯线附近。
      // 增长弱正、通胀偏低 → 落在「衰退」象限但贴近「复苏」边界，呈筑底、向复苏过渡态势。
      phase: '衰退',
      pos: { growth: -12, inflation: -34 },
      posSource: 'ai',
      note: '默认研判（可编辑）：2026-08 数据——CPI +0.9%（近通缩）、PPI +1.8%（温和回正）、规上工业 +5.3%、社零 +2.6%（内需偏弱）、固投 -6.7%（地产拖累）、制造业 PMI 在 50 荣枯线附近。综合判断：增长弱正、通胀偏低，定位为「衰退」象限但贴近「复苏」边界，属筑底、向复苏过渡阶段——债券与黄金相对占优，权益待政策与需求进一步企稳后提升。请结合最新 PMI/CPI/社融自行核实并微调落点。',
      updatedAt: todayStr,
    },
    assets: [
      { id: 'equity', name: 'A股股票', score: 55, view: '中性' },
      { id: 'hkequity', name: '港股', score: 62, view: '乐观' },
      { id: 'usequity', name: '美股', score: 45, view: '谨慎' },
      { id: 'bond', name: '债券', score: 70, view: '乐观' },
      { id: 'gold', name: '黄金', score: 72, view: '乐观' },
      { id: 'commodity', name: '商品', score: 38, view: '中性' },
      { id: 'cash', name: '现金/货币', score: 50, view: '中性' },
    ],
    monthlyStrategy: {
      ym: todayStr.slice(0, 7),
      content: '',
    },
  }

  return {
    principles,
    l1,
    methods,
    targets,
    trades,
    reviews,
    observations,
    memos,
    materials,
    logs,
    dashboard,
    analysis: { targets: {}, macro: null }, // 实时分析结果缓存（垂类 Agent 分析输出）
    version: 'v2.0',
  }
}
