/**
 * 预置种子 / 冷启动注入数据。
 * 数据准则（2026-08-26 起）：不再包含示例数据，直接以用户真实持仓与《个人投资体系总纲》内容工作。
 * - 5 条核心底层信念 → 原则卡片 IS-2026-001~005
 * - 六大融合策略（分场景、带边界红线）→ 方法 M-2026-001~006
 * - 能力圈：科技 / 消费 / 医药 / 资源 / 红利 / 黄金 / 债券
 * - 个人硬约束：资金周期 2 年；最大回撤 ≤ 30%；中线+长线持仓；日均研究 0.5-1h
 * - 真实持仓：现金12万 + 10只场内/场外基金 + 5只美股；关注方向：电网ETF
 */
import {
  createIS,
  createMethod,
  createTarget,
  createTrade,
  createObservation,
  createL1,
  createChangeLog,
  createMemo,
  createFund,
  createIndustryWatch,
  createStrategy,
  createMonthlyStrategy,
} from '../models/schemas'

export function seedData() {
  // ---------- 投资原则 IS（5 张，对应总纲 5 条核心底层信念） ----------
  const principles = [
    createIS({
      id: 'IS-2026-001',
      title: '风险优先，生存第一',
      module: '投资哲学',
      category: '宪法级',
      confidence: 95,
      validationPlan: '任何决策先问：最坏情况下是否会永久性亏损本金？若会，则放弃；最大回撤任何时候不超过 30%。',
      status: '已采纳',
      statement: '投资首要目标是规避永久性本金亏损，其次才是博取超额收益。所有盈利都是市场馈赠，活着才有复利机会。',
      source: '个人投资体系总纲（人机共创融合版）· 核心底层信念 ①',
      scope: '全部投资决策与风控底线，任何策略不得违背',
      relatedErrIds: ['ERR-2026-002', 'ERR-2026-004'],
      isConstitution: true,
      createdAt: '2026-08-21',
      updatedAt: '2026-08-21',
      isSample: false,
    }),
    createIS({
      id: 'IS-2026-002',
      title: '不懂不做，严守能力圈',
      module: '投资哲学',
      category: '宪法级',
      confidence: 93,
      validationPlan: '买入前必须能用三句话讲清商业模式、驱动因素与风险；能力圈外（非科技/消费/医药/资源/红利/黄金/债券）标的拒绝跟风。',
      status: '已采纳',
      statement: '不参与逻辑无法自洽、商业模式看不懂、驱动因素不清晰、风险不可预判的标的，拒绝跟风交易。',
      source: '个人投资体系总纲 · 核心底层信念 ②',
      scope: '标的研究与选股；能力圈覆盖：科技 / 消费 / 医药 / 资源 / 红利 / 黄金 / 债券',
      relatedErrIds: ['ERR-2026-003'],
      isConstitution: true,
      createdAt: '2026-08-21',
      updatedAt: '2026-08-21',
      isSample: false,
    }),
    createIS({
      id: 'IS-2026-003',
      title: '价格是情绪，价值是锚点',
      module: '估值纪律',
      category: '宪法级',
      confidence: 90,
      validationPlan: '买入必须留有安全边际；估值分位 > 80% 禁止追高；短期尊重趋势、长期坚守价值，不做纯价格博弈。',
      status: '已采纳',
      statement: '短期市场由资金、情绪、趋势驱动，长期由企业基本面、产业逻辑、现金流决定。尊重短期趋势，坚守长期价值。',
      source: '个人投资体系总纲 · 核心底层信念 ③（融合价值投资/趋势动量/反身性）',
      scope: '买入定价、持仓评估、止盈止损',
      relatedErrIds: ['ERR-2026-001'],
      isConstitution: true,
      createdAt: '2026-08-21',
      updatedAt: '2026-08-21',
      isSample: false,
    }),
    createIS({
      id: 'IS-2026-004',
      title: '超额收益来自认知差与逆向性',
      module: '收益来源',
      category: '可复用',
      confidence: 86,
      validationPlan: '不通过频繁交易、追涨杀跌博取收益；只在共识偏差、市场非理性、优质标的错杀时出手。',
      status: '已采纳',
      statement: '长期超额收益源于大众共识的偏差、市场短期非理性与优质标的错杀，而非频繁交易与追涨杀跌。',
      source: '个人投资体系总纲 · 核心底层信念 ④（融合逆向投资/成长价值）',
      scope: '策略选择与买入时机',
      relatedErrIds: ['ERR-2026-005'],
      isConstitution: false,
      createdAt: '2026-08-21',
      updatedAt: '2026-08-21',
      isSample: false,
    }),
    createIS({
      id: 'IS-2026-005',
      title: '周期轮回，资产轮动',
      module: '大类资产配置',
      category: '可复用',
      confidence: 84,
      validationPlan: '以宏观周期（复苏/过热/滞胀/衰退）为顶层调度，动态调整股票/债券/黄金/现金配置；以季度/半年为调仓周期，权益仓位不低于 30%。',
      status: '已采纳',
      statement: '经济与市场存在周期性规律，不同周期阶段适配不同大类资产；通过大类资产配置平滑组合波动，提升风险调整后收益。',
      source: '个人投资体系总纲 · 核心底层信念 ⑤（融合宏观大类资产配置哲学）',
      scope: '组合顶层调度与仓位总上限',
      relatedErrIds: ['ERR-2026-006'],
      isConstitution: false,
      createdAt: '2026-08-21',
      updatedAt: '2026-08-21',
      isSample: false,
    }),
  ]

  // ---------- L1 投资哲学（只读视图，宪法级细分） ----------
  const l1 = [
    createL1({
      id: 'L1-2026-001',
      category: '赚钱逻辑',
      title: '风险优先，活着才有复利',
      rule: '首要目标是规避永久性本金亏损，其次才是超额收益；盈利是市场馈赠。',
      boundary: '任何可能导致本金永久性损失的操作（加杠杆、押注超长周期价值回归）。',
      reason: '复利非线性：大幅回撤的修复时间远大于下跌时长，永久性亏损无法用时间抹平。',
      sourceIsId: 'IS-2026-001',
      isSample: false,
    }),
    createL1({
      id: 'L1-2026-002',
      category: '赚钱逻辑',
      title: '价值为锚，情绪为扰动',
      rule: '短期看资金与情绪，长期看基本面与现金流；尊重趋势但坚守价值。',
      boundary: '纯价格博弈、题材炒作、无基本面支撑的趋势追高。',
      reason: '价格围绕价值波动，安全边际可覆盖认知误差。',
      sourceIsId: 'IS-2026-003',
      isSample: false,
    }),
    createL1({
      id: 'L1-2026-003',
      category: '赚钱逻辑',
      title: '超额来自认知差与逆向',
      rule: '在共识偏差、市场非理性、优质标的错杀时出手，赚情绪修复与价值回归的钱。',
      boundary: '频繁交易、追涨杀跌、参与大众共识最狂热的方向。',
      reason: '频繁交易侵蚀收益，共识最拥挤处赔率最差。',
      sourceIsId: 'IS-2026-004',
      isSample: false,
    }),
    createL1({
      id: 'L1-2026-004',
      category: '赚钱逻辑',
      title: '周期轮回，资产轮动',
      rule: '以宏观周期为顶层调度，动态配置股票/债券/黄金/现金四类资产，平滑 2 年资金周期波动。',
      boundary: '不做月度级高频轮动、不用于个股择时。',
      reason: '不同周期阶段大类资产相对收益显著不同，配置可降低单一资产系统性风险。',
      sourceIsId: 'IS-2026-005',
      isSample: false,
    }),
    createL1({
      id: 'L1-2026-005',
      category: '不碰什么',
      title: '能力圈外不投',
      rule: '无法用三句话讲清商业模式、驱动因素与风险的标的，一律不投。',
      boundary: '能力圈（科技/消费/医药/资源/红利/黄金/债券）之外的陌生行业与复杂衍生品。',
      reason: '认知缺口是亏损的主要来源，不懂不做是成熟投资者的核心原则。',
      sourceIsId: 'IS-2026-002',
      isSample: false,
    }),
    createL1({
      id: 'L1-2026-006',
      category: '不碰什么',
      title: '不用杠杆，不赌超长周期',
      rule: '任何情形不使用融资融券、场外配资；不押注超过资金周期（2 年）的价值回归。',
      boundary: '杠杆头寸、3 年以上才可能兑现的逻辑。',
      reason: '杠杆会剥夺时间这个朋友；价值回归周期不可控，可能超出资金使用期限。',
      sourceIsId: 'IS-2026-001',
      isSample: false,
    }),
    createL1({
      id: 'L1-2026-007',
      category: '不碰什么',
      title: '不做纯技术面 / 纯题材交易',
      rule: '所有趋势操作必须绑定基本面合格标的；纯题材、无业绩支撑的赛道炒作一律不参与。',
      boundary: '震荡市中的假突破、高位鱼尾行情、情绪快速轮动题材。',
      reason: '纯技术趋势无基本面支撑时极易失效，题材炒作违背认知差原则。',
      sourceIsId: 'IS-2026-004',
      isSample: false,
    }),
    createL1({
      id: 'L1-2026-008',
      category: '风险底线',
      title: '最大回撤不超过 30%',
      rule: '组合回撤以 30% 为硬性上限，偏稳健，可接受适度波动，不可激进。',
      boundary: '任何导致回撤突破 30% 的加仓或风险暴露。',
      reason: '30% 回撤是个人可承受边界，风控规则为体系最高优先级。',
      sourceIsId: 'IS-2026-001',
      isSample: false,
    }),
    createL1({
      id: 'L1-2026-009',
      category: '风险底线',
      title: '仓位三层约束',
      rule: '单票 ≤ 组合 20%，单一行业 ≤ 40%，逆向投资单票 ≤ 5%。',
      boundary: '单一标的或行业集中度过高、逆向仓超出试错成本上限。',
      reason: '分散非系统性风险，防止黑天鹅对组合造成致命打击；逆向只做机动试错。',
      sourceIsId: 'IS-2026-001',
      isSample: false,
    }),
  ]

  // ---------- L2 投资方法（六大融合策略，对应总纲第四章） ----------
  const methods = [
    createMethod({
      id: 'M-2026-001',
      name: '宏观大类资产配置（顶层调度 · 权重 10%）',
      scenario: '组合顶层资产分配、经济周期拐点、政策转向期、系统性风险上升阶段。',
      assumptions: '经济运行存在复苏/过热/滞胀/衰退周期规律；不同周期大类资产相对收益显著不同。',
      steps: [
        '判断当前周期阶段（复苏/过热/滞胀/衰退）与流动性环境',
        '动态调整股票/债券/黄金/现金四大类资产配置比例',
        '周期向上提升权益仓位；周期向下增配债券与现金；风险事件增配黄金对冲',
        '以季度/半年为调仓周期，大类配置决定各策略总仓位上限',
        '权益资产最低仓位不低于 30%，避免完全踏空牛市',
      ],
      limitations: '宏观周期判断难度高，拐点极易误判；不用于个股择时，不作为收益增强核心手段。',
      status: '启用',
      relatedIsIds: ['IS-2026-005'],
      version: 'v1.0',
      isSample: false,
    }),
    createMethod({
      id: 'M-2026-002',
      name: '价值投资策略（底盘基石 · 权重 50%）',
      scenario: '核心持仓配置、震荡市、熊市底部、成熟期优质标的布局。',
      assumptions: '企业存在可测算的内在价值；价格长期向内在价值回归；安全边际可覆盖认知误差。',
      steps: [
        '以企业内在价值为锚，优选商业模式稳定、现金流扎实、ROE 持续稳健的标的',
        '严格坚守安全边际，仅在价格显著低于合理价值区间时分批买入',
        '连续两个季度核心盈利指标下滑且无复苏迹象时，立即重估内在价值，不硬扛价值陷阱',
        '估值回归至合理区间后，不再按价值逻辑加仓',
      ],
      limitations: '价值回归周期不可控，可能超出资金使用期限；需警惕基本面恶化的价值陷阱。',
      status: '启用',
      relatedIsIds: ['IS-2026-001', 'IS-2026-003'],
      version: 'v1.0',
      isSample: false,
    }),
    createMethod({
      id: 'M-2026-003',
      name: 'GARP 合理成长策略（收益主力 · 权重 30%）',
      scenario: '景气上行行业、结构性牛市、业绩确定性强的成长标的。',
      assumptions: '盈利增速是中期股价核心驱动；行业景气与企业增速具备 1-3 年持续性。',
      steps: [
        '以「业绩增速匹配估值水平」为核心标准选股',
        '精选行业渗透率提升、公司份额持续扩张的标的',
        '以产业趋势与政策导向为核心判断依据，财报与估值作验证辅助',
        'PE/PEG 显著高于行业中枢与自身历史分位时，停止加仓',
        '行业景气见顶或增速不及预期时，立即终止成长逻辑，切换价值评估或止盈离场',
      ],
      limitations: '对景气拐点判断要求极高；增速不及预期易遭遇「估值+业绩」双杀；避免将短期景气错判为长期能力。',
      status: '启用',
      relatedIsIds: ['IS-2026-003', 'IS-2026-004'],
      version: 'v1.0',
      isSample: false,
    }),
    createMethod({
      id: 'M-2026-004',
      name: '轻量化趋势策略（择时辅助 · 辅助工具）',
      scenario: '单边趋势行情、板块资金共振、右侧修复阶段。',
      assumptions: '资金与情绪具备惯性；趋势形成后短期不会立即反转；价格信号领先于基本面共识扩散。',
      steps: [
        '仅作为入场与仓位管理工具，不独立选股',
        '在基本面达标前提下，趋势确立时加仓提升资金效率',
        '趋势破位时减仓止盈，规避回撤',
        '震荡市自动停用趋势规则，避免频繁止损',
        '绝不追高鱼尾行情',
      ],
      limitations: '震荡市反复假突破，止损成本高；存在滞后性，无法精准捕捉拐点；纯技术趋势无基本面支撑时极易失效。',
      status: '启用',
      relatedIsIds: ['IS-2026-003', 'IS-2026-004'],
      version: 'v1.0',
      isSample: false,
    }),
    createMethod({
      id: 'M-2026-005',
      name: '逆向投资策略（机动超额 · 辅助工具）',
      scenario: '市场极端悲观、优质标的短期非致命利空、行业系统性情绪错杀。',
      assumptions: '市场情绪会周期性极端偏离基本面；短期非致命利空不改变企业长期内在价值。',
      steps: [
        '确认企业基本面未受损、利空为短期性',
        '分批左侧布局，赚取情绪修复与价值回归双重收益',
        '下跌趋势未企稳前不一次性满仓',
        '逆向仓位单票不超过总仓位的 5%，严格控制试错成本',
        '不抄底基本面永久恶化、被技术/政策颠覆的标的',
      ],
      limitations: '左侧抄底容易过早，逆势持仓心理压力大；难以精准区分「短期错杀」与「基本面永久恶化」。',
      status: '待验证',
      relatedIsIds: ['IS-2026-004'],
      version: 'v1.0',
      isSample: false,
    }),
    createMethod({
      id: 'M-2026-006',
      name: '防御型风控策略（全程兜底 · 最高优先级）',
      scenario: '全市场环境、所有持仓与交易动作。',
      assumptions: '复利非线性：大幅回撤的修复时长远大于下跌时长；永久性亏损无法通过时间抹平。',
      steps: [
        '仓位上限约束：组合总仓位与单票/行业集中度不超硬规则',
        '集中度约束：单票 ≤ 20%，单一行业 ≤ 40%，逆向单票 ≤ 5%',
        '止损止盈规则：跌破防守线按计划减仓，不因侥幸拖延',
        '不因市场狂热、短期踏空放松风控标准',
        '风控规则为体系最高优先级，任何策略均不得突破',
      ],
      limitations: '牛市中容易偏保守，阶段性跑输激进体系，牺牲部分上行弹性——此为体系有意为之。',
      status: '启用',
      relatedIsIds: ['IS-2026-001'],
      version: 'v1.0',
      isSample: false,
    }),
  ]

  // ---------- L3 标的研究（真实持仓 + 电网ETF观察） ----------
  const targets = [
    createTarget({
      id: 'T-CASH',
      name: '现金/货币',
      code: 'CASH',
      currency: 'CNY',
      businessModel: '闲置现金与货币类资产，用于流动性与大类资产调仓储备。',
      moat: '流动性最高，零风险，作为组合的安全垫与配置缓冲。',
      keyFinancials: { currentPrice: null, pe: null, roe: null, marketCap: '' },
      riskPoints: ['长期持有现金面临通胀与机会成本'],
      valuationRange: { currentPercentile: null, tiers: ['极冷', '冷', '中', '热', '极热'] },
      trackingPoints: ['现金占比、调仓需求'],
      relatedIsIds: ['IS-2026-005'],
      relatedErrIds: [],
      stage: '跟踪中',
      isSample: false,
    }),
    createTarget({
      id: 'T-159139',
      name: '159139',
      code: '159139',
      currency: 'CNY',
      businessModel: '跟踪特定指数的场内 ETF（代码 159139）。',
      moat: '',
      keyFinancials: { currentPrice: null, pe: null, roe: null, marketCap: '' },
      riskPoints: [],
      valuationRange: { currentPercentile: null, tiers: ['极冷', '冷', '中', '热', '极热'] },
      trackingPoints: ['基金净值与指数跟踪', '行业景气'],
      relatedIsIds: [],
      relatedErrIds: [],
      stage: '跟踪中',
      isSample: false,
    }),
    createTarget({
      id: 'T-159770',
      name: '159770',
      code: '159770',
      currency: 'CNY',
      businessModel: '跟踪特定指数的场内 ETF（代码 159770）。',
      moat: '',
      keyFinancials: { currentPrice: null, pe: null, roe: null, marketCap: '' },
      riskPoints: [],
      valuationRange: { currentPercentile: null, tiers: ['极冷', '冷', '中', '热', '极热'] },
      trackingPoints: ['基金净值与指数跟踪', '行业景气'],
      relatedIsIds: [],
      relatedErrIds: [],
      stage: '跟踪中',
      isSample: false,
    }),
    createTarget({
      id: 'T-159994',
      name: '159994',
      code: '159994',
      currency: 'CNY',
      businessModel: '跟踪特定指数的场内 ETF（代码 159994）。',
      moat: '',
      keyFinancials: { currentPrice: null, pe: null, roe: null, marketCap: '' },
      riskPoints: [],
      valuationRange: { currentPercentile: null, tiers: ['极冷', '冷', '中', '热', '极热'] },
      trackingPoints: ['基金净值与指数跟踪', '行业景气'],
      relatedIsIds: [],
      relatedErrIds: [],
      stage: '跟踪中',
      isSample: false,
    }),
    createTarget({
      id: 'T-512480',
      name: '512480（半导体ETF）',
      code: '512480',
      currency: 'CNY',
      businessModel: '跟踪中证全指半导体指数的场内 ETF，聚焦半导体产业链（设备/制造/设计）。',
      moat: '流动性好的半导体行业指数工具，用于行业景气上行期的弹性配置。',
      keyFinancials: { currentPrice: null, pe: null, roe: null, marketCap: '' },
      riskPoints: ['半导体行业周期波动大', '估值敏感'],
      valuationRange: { currentPercentile: null, tiers: ['极冷', '冷', '中', '热', '极热'] },
      trackingPoints: ['半导体景气度', '国产替代进程', '基金净值跟踪误差'],
      relatedIsIds: ['IS-2026-002'],
      relatedErrIds: [],
      stage: '跟踪中',
      isSample: false,
    }),
    createTarget({
      id: 'T-512630',
      name: '512630',
      code: '512630',
      currency: 'CNY',
      businessModel: '跟踪特定指数的场内 ETF（代码 512630）。',
      moat: '',
      keyFinancials: { currentPrice: null, pe: null, roe: null, marketCap: '' },
      riskPoints: [],
      valuationRange: { currentPercentile: null, tiers: ['极冷', '冷', '中', '热', '极热'] },
      trackingPoints: ['基金净值与指数跟踪', '行业景气'],
      relatedIsIds: [],
      relatedErrIds: [],
      stage: '跟踪中',
      isSample: false,
    }),
    createTarget({
      id: 'T-001194',
      name: '001194',
      code: '001194',
      currency: 'CNY',
      businessModel: '场外主动基金（代码 001194）。',
      moat: '',
      keyFinancials: { currentPrice: null, pe: null, roe: null, marketCap: '' },
      riskPoints: [],
      valuationRange: { currentPercentile: null, tiers: ['极冷', '冷', '中', '热', '极热'] },
      trackingPoints: ['基金净值与业绩表现', '经理与持仓动向'],
      relatedIsIds: [],
      relatedErrIds: [],
      stage: '跟踪中',
      isSample: false,
    }),
    createTarget({
      id: 'T-001917',
      name: '001917',
      code: '001917',
      currency: 'CNY',
      businessModel: '场外主动基金（代码 001917）。',
      moat: '',
      keyFinancials: { currentPrice: null, pe: null, roe: null, marketCap: '' },
      riskPoints: [],
      valuationRange: { currentPercentile: null, tiers: ['极冷', '冷', '中', '热', '极热'] },
      trackingPoints: ['基金净值与业绩表现', '经理与持仓动向'],
      relatedIsIds: [],
      relatedErrIds: [],
      stage: '跟踪中',
      isSample: false,
    }),
    createTarget({
      id: 'T-673010',
      name: '673010',
      code: '673010',
      currency: 'CNY',
      businessModel: '场外主动基金（代码 673010）。',
      moat: '',
      keyFinancials: { currentPrice: null, pe: null, roe: null, marketCap: '' },
      riskPoints: [],
      valuationRange: { currentPercentile: null, tiers: ['极冷', '冷', '中', '热', '极热'] },
      trackingPoints: ['基金净值与业绩表现', '经理与持仓动向'],
      relatedIsIds: [],
      relatedErrIds: [],
      stage: '跟踪中',
      isSample: false,
    }),
    createTarget({
      id: 'T-004433',
      name: '004433',
      code: '004433',
      currency: 'CNY',
      businessModel: '场外主动基金（代码 004433）。',
      moat: '',
      keyFinancials: { currentPrice: null, pe: null, roe: null, marketCap: '' },
      riskPoints: [],
      valuationRange: { currentPercentile: null, tiers: ['极冷', '冷', '中', '热', '极热'] },
      trackingPoints: ['基金净值与业绩表现', '经理与持仓动向'],
      relatedIsIds: [],
      relatedErrIds: [],
      stage: '跟踪中',
      isSample: false,
    }),
    createTarget({
      id: 'T-008923',
      name: '008923',
      code: '008923',
      currency: 'CNY',
      businessModel: '场外主动基金（代码 008923）。',
      moat: '',
      keyFinancials: { currentPrice: null, pe: null, roe: null, marketCap: '' },
      riskPoints: [],
      valuationRange: { currentPercentile: null, tiers: ['极冷', '冷', '中', '热', '极热'] },
      trackingPoints: ['基金净值与业绩表现', '经理与持仓动向'],
      relatedIsIds: [],
      relatedErrIds: [],
      stage: '跟踪中',
      isSample: false,
    }),
    createTarget({
      id: 'T-TSLL',
      name: 'TSLL（特斯拉杠杆ETF）',
      code: 'TSLL',
      currency: 'USD',
      businessModel: '美股场内杠杆 ETF，跟踪特斯拉（TSLA）单日表现倍数（美股）。',
      moat: '高弹性工具，仅用于对特斯拉短期观点的表达，波动与损耗大。',
      keyFinancials: { currentPrice: null, pe: null, roe: null, marketCap: '' },
      riskPoints: ['杠杆ETF存在每日复利损耗', '特斯拉个股波动极大', '不适合长期持有'],
      valuationRange: { currentPercentile: null, tiers: ['极冷', '冷', '中', '热', '极热'] },
      trackingPoints: ['特斯拉交付与财报', '美股科技情绪'],
      relatedIsIds: ['IS-2026-002'],
      relatedErrIds: ['ERR-2026-002'],
      stage: '跟踪中',
      isSample: false,
    }),
    createTarget({
      id: 'T-MU',
      name: 'MU（美光科技）',
      code: 'MU',
      currency: 'USD',
      businessModel: '全球领先的内存（DRAM/NAND）供应商，受益于存储周期上行与 AI 数据中心需求。',
      moat: '存储寡头格局 + 制程与产能壁垒 + AI/数据中心需求弹性。',
      keyFinancials: { currentPrice: null, pe: null, roe: null, marketCap: '' },
      riskPoints: ['存储周期波动', 'AI 需求兑现节奏', '价格周期下行'],
      valuationRange: { currentPercentile: null, tiers: ['极冷', '冷', '中', '热', '极热'] },
      trackingPoints: ['DRAM/NAND 价格', 'HBM 出货', '数据中心资本开支'],
      relatedIsIds: ['IS-2026-002'],
      relatedErrIds: [],
      stage: '跟踪中',
      isSample: false,
    }),
    createTarget({
      id: 'T-ALB',
      name: 'ALB（雅保）',
      code: 'ALB',
      currency: 'USD',
      businessModel: '全球锂化工龙头（Albemarle），聚焦锂盐与特种化学品，受益于新能源与储能需求。',
      moat: '锂资源储量与成本优势 + 全球化客户与产能布局。',
      keyFinancials: { currentPrice: null, pe: null, roe: null, marketCap: '' },
      riskPoints: ['锂价周期波动', '新能源需求不及预期', '扩产导致供给过剩'],
      valuationRange: { currentPercentile: null, tiers: ['极冷', '冷', '中', '热', '极热'] },
      trackingPoints: ['碳酸锂价格', '储能装机', '锂矿供给'],
      relatedIsIds: ['IS-2026-002'],
      relatedErrIds: [],
      stage: '跟踪中',
      isSample: false,
    }),
    createTarget({
      id: 'T-BMNR',
      name: 'BMNR',
      code: 'BMNR',
      currency: 'USD',
      businessModel: '美股标的（代码 BMNR）。',
      moat: '',
      keyFinancials: { currentPrice: null, pe: null, roe: null, marketCap: '' },
      riskPoints: [],
      valuationRange: { currentPercentile: null, tiers: ['极冷', '冷', '中', '热', '极热'] },
      trackingPoints: ['标的公司基本面与业绩'],
      relatedIsIds: [],
      relatedErrIds: [],
      stage: '跟踪中',
      isSample: false,
    }),
    createTarget({
      id: 'T-ARKK',
      name: 'ARKK（方舟创新ETF）',
      code: 'ARKK',
      currency: 'USD',
      businessModel: '美股 ARK 创新主题主动 ETF，重仓颠覆性创新科技公司。',
      moat: '聚焦明星成长赛道（AI/基因/新能源），高弹性高波动。',
      keyFinancials: { currentPrice: null, pe: null, roe: null, marketCap: '' },
      riskPoints: ['高估值成长股波动大', '利率上行压制', '持仓集中'],
      valuationRange: { currentPercentile: null, tiers: ['极冷', '冷', '中', '热', '极热'] },
      trackingPoints: ['美股科技成长风格', '利率环境'],
      relatedIsIds: ['IS-2026-002'],
      relatedErrIds: [],
      stage: '跟踪中',
      isSample: false,
    }),
    createTarget({
      id: 'T-DW',
      name: '电网ETF',
      code: '',
      currency: 'CNY',
      businessModel: '跟踪电网上中游产业链的 ETF（电网建设/设备/特高压），受益于电力基建投资与新能源并网。',
      moat: '特高压与电力设备招标景气，电网投资确定性高。',
      keyFinancials: { currentPrice: null, pe: null, roe: null, marketCap: '' },
      riskPoints: ['电网投资节奏波动', '设备价格竞争'],
      valuationRange: { currentPercentile: null, tiers: ['极冷', '冷', '中', '热', '极热'] },
      trackingPoints: ['电网投资额', '特高压招标', '电力设备订单'],
      relatedIsIds: ['IS-2026-002', 'IS-2026-005'],
      relatedErrIds: [],
      stage: '研究中',
      isSample: false,
    }),
  ]

  // ---------- L4 交易日志（真实持仓：现金 + 场内ETF + 场外基金 + 美股） ----------
  // 市值口径：quantity=1，price=当前持仓市值（本币），amount=市值，避免虚构份额。
  const trades = [
    createTrade({
      id: 'TR-CASH',
      date: '2026-08-25',
      targetId: 'T-CASH',
      targetName: '现金/货币',
      direction: '做多',
      quantity: 1,
      price: 120000,
      currency: 'CNY',
      amount: 120000,
      industry: '现金/货币',
      memoId: '',
      status: '已归档',
      decisionContext: {
        marketEnvironment: '配置储备',
        valuation: '',
        mentality: '作为流动性储备与大类资产调仓缓冲',
        expectedReturn: '',
        stopLoss: '',
      },
      isSample: false,
    }),
    createTrade({
      id: 'TR-159139',
      date: '2026-08-25',
      targetId: 'T-159139',
      targetName: '159139',
      direction: '做多',
      quantity: 1,
      price: 1440,
      currency: 'CNY',
      amount: 1440,
      industry: 'ETF',
      memoId: '',
      status: '已归档',
      decisionContext: {},
      isSample: false,
    }),
    createTrade({
      id: 'TR-159770',
      date: '2026-08-25',
      targetId: 'T-159770',
      targetName: '159770',
      direction: '做多',
      quantity: 1,
      price: 4643,
      currency: 'CNY',
      amount: 4643,
      industry: 'ETF',
      memoId: '',
      status: '已归档',
      decisionContext: {},
      isSample: false,
    }),
    createTrade({
      id: 'TR-159994',
      date: '2026-08-25',
      targetId: 'T-159994',
      targetName: '159994',
      direction: '做多',
      quantity: 1,
      price: 4475,
      currency: 'CNY',
      amount: 4475,
      industry: 'ETF',
      memoId: '',
      status: '已归档',
      decisionContext: {},
      isSample: false,
    }),
    createTrade({
      id: 'TR-512480',
      date: '2026-08-25',
      targetId: 'T-512480',
      targetName: '512480（半导体ETF）',
      direction: '做多',
      quantity: 1,
      price: 4505,
      currency: 'CNY',
      amount: 4505,
      industry: '半导体',
      memoId: '',
      status: '已归档',
      decisionContext: {},
      isSample: false,
    }),
    createTrade({
      id: 'TR-512630',
      date: '2026-08-25',
      targetId: 'T-512630',
      targetName: '512630',
      direction: '做多',
      quantity: 1,
      price: 4622,
      currency: 'CNY',
      amount: 4622,
      industry: 'ETF',
      memoId: '',
      status: '已归档',
      decisionContext: {},
      isSample: false,
    }),
    createTrade({
      id: 'TR-001194',
      date: '2026-08-25',
      targetId: 'T-001194',
      targetName: '001194',
      direction: '做多',
      quantity: 1,
      price: 34040,
      currency: 'CNY',
      amount: 34040,
      industry: '基金',
      memoId: '',
      status: '已归档',
      decisionContext: {},
      isSample: false,
    }),
    createTrade({
      id: 'TR-001917',
      date: '2026-08-25',
      targetId: 'T-001917',
      targetName: '001917',
      direction: '做多',
      quantity: 1,
      price: 9226,
      currency: 'CNY',
      amount: 9226,
      industry: '基金',
      memoId: '',
      status: '已归档',
      decisionContext: {},
      isSample: false,
    }),
    createTrade({
      id: 'TR-673010',
      date: '2026-08-25',
      targetId: 'T-673010',
      targetName: '673010',
      direction: '做多',
      quantity: 1,
      price: 8862,
      currency: 'CNY',
      amount: 8862,
      industry: '基金',
      memoId: '',
      status: '已归档',
      decisionContext: {},
      isSample: false,
    }),
    createTrade({
      id: 'TR-004433',
      date: '2026-08-25',
      targetId: 'T-004433',
      targetName: '004433',
      direction: '做多',
      quantity: 1,
      price: 8142,
      currency: 'CNY',
      amount: 8142,
      industry: '基金',
      memoId: '',
      status: '已归档',
      decisionContext: {},
      isSample: false,
    }),
    createTrade({
      id: 'TR-008923',
      date: '2026-08-25',
      targetId: 'T-008923',
      targetName: '008923',
      direction: '做多',
      quantity: 1,
      price: 4335,
      currency: 'CNY',
      amount: 4335,
      industry: '基金',
      memoId: '',
      status: '已归档',
      decisionContext: {},
      isSample: false,
    }),
    createTrade({
      id: 'TR-TSLL',
      date: '2026-08-25',
      targetId: 'T-TSLL',
      targetName: 'TSLL（特斯拉杠杆ETF）',
      direction: '做多',
      quantity: 1,
      price: 1585,
      currency: 'USD',
      amount: 1585,
      industry: '美股科技',
      memoId: '',
      status: '已归档',
      isOutOfBoundary: true, // 杠杆ETF波动大，标记边界外待核
      decisionContext: {
        marketEnvironment: '美股 AI/特斯拉主题',
        valuation: '杠杆ETF不适用估值分位',
        mentality: '杠杆工具波动极大，需复核持仓周期',
        expectedReturn: '',
        stopLoss: '',
      },
      isSample: false,
    }),
    createTrade({
      id: 'TR-MU',
      date: '2026-08-25',
      targetId: 'T-MU',
      targetName: 'MU（美光科技）',
      direction: '做多',
      quantity: 1,
      price: 1466,
      currency: 'USD',
      amount: 1466,
      industry: '半导体',
      memoId: '',
      status: '已归档',
      decisionContext: {},
      isSample: false,
    }),
    createTrade({
      id: 'TR-ALB',
      date: '2026-08-25',
      targetId: 'T-ALB',
      targetName: 'ALB（雅保）',
      direction: '做多',
      quantity: 1,
      price: 931,
      currency: 'USD',
      amount: 931,
      industry: '新能源材料',
      memoId: '',
      status: '已归档',
      decisionContext: {},
      isSample: false,
    }),
    createTrade({
      id: 'TR-BMNR',
      date: '2026-08-25',
      targetId: 'T-BMNR',
      targetName: 'BMNR',
      direction: '做多',
      quantity: 1,
      price: 444,
      currency: 'USD',
      amount: 444,
      industry: '美股',
      memoId: '',
      status: '已归档',
      decisionContext: {},
      isSample: false,
    }),
    createTrade({
      id: 'TR-ARKK',
      date: '2026-08-25',
      targetId: 'T-ARKK',
      targetName: 'ARKK（方舟创新ETF）',
      direction: '做多',
      quantity: 1,
      price: 260,
      currency: 'USD',
      amount: 260,
      industry: '美股成长',
      memoId: '',
      status: '已归档',
      decisionContext: {},
      isSample: false,
    }),
  ]

  // ---------- L5 复盘与错误（示例已清除，按用户真实记录填写） ----------
  const reviews = []

  // ---------- L6 观察灵感（仅保留用户真实灵感） ----------
  const observations = [
    createObservation({
      id: 'OB-007',
      title: '看好的方向：电网产业链景气与政策共振',
      source: '个人研判',
      sourceType: '灵感',
      summary: '新能源并网提速 + 电网投资加码，特高压与配网改造带来设备订单景气，关注电网ETF的建仓信号。',
      status: '待归档',
      relatedTargetIds: ['T-DW'],
      relatedMethodIds: ['M-2026-001'],
      relatedErrIds: [],
      createdAt: '2026-08-25',
      isSample: false,
    }),
  ]

  // ---------- 10. 投资备忘录 ----------
  const memos = []

  // ---------- 8. 资料-卡片索引 ----------
  const materials = []

  // ---------- 9. 体系变更日志 ----------
  const logs = [
    createChangeLog({
      id: 'CL-001',
      type: '+',
      description: '植入《个人投资体系总纲-人机共创融合版》v2.0：5 条核心底层信念（IS-2026-001~005）与六大融合策略（M-2026-001~006）。',
      version: 'v2.0',
      createdAt: '2026-08-21',
      isSample: false,
    }),
    createChangeLog({
      id: 'CL-002',
      type: '~',
      description: '能力圈边界定义：科技 / 消费 / 医药 / 资源 / 红利 / 黄金 / 债券；新增黄金 ETF 与红利 ETF 大类资产观察标的。',
      version: 'v2.0',
      createdAt: '2026-08-21',
      isSample: false,
    }),
  ]

  // ---------- 11. 首页看板状态（市场时钟 / 资产吸引力 / 本月策略） ----------
  const todayStr = new Date().toISOString().slice(0, 10)
  const dashboard = {
    marketClock: {
      // 默认定位依据（2026-08，国家统计局 2026-08-17 发布）：CPI +0.9%（近通缩）、PPI +1.8%（温和回正）、
      // 规上工业增加值 +5.3%、社零 +2.6%（内需偏弱）、固投 -6.7%（地产拖累）、PMI 在 50 荣枯线附近。
      // 增长弱正、通胀偏低 → 落在「衰退」象限但贴近「复苏」边界，呈筑底、向复苏过渡态势。
      phase: '衰退',
      pos: { growth: -12, inflation: -34 },
      posSource: 'ai',
      note: '默认研判（可编辑）：2026-08 数据——CPI +0.9%（近通缩）、PPI +1.8%（温和回正）、规上工业 +5.3%、社零 +2.6%（内需偏弱）、固投 -6.7%（地产拖累）、制造业 PMI 在 50 荣枯线附近。综合判断：增长弱正、通胀偏低，定位为「衰退」象限但贴近「复苏」边界，属筑底、向复苏过渡阶段——债券与黄金相对占优，权益待政策与需求进一步企稳后提升。请结合最新 PMI/CPI/社融自行核实并微调落点。',
      updatedAt: todayStr,
    },
    assets: [
      { id: 'equity', name: 'A股股票', score: 55, view: '中性' },
      { id: 'hkequity', name: '港股', score: 62, view: '乐观' },
      { id: 'usequity', name: '美股', score: 45, view: '谨慎' },
      { id: 'bond', name: '债券', score: 70, view: '乐观' },
      { id: 'gold', name: '黄金', score: 72, view: '乐观' },
      { id: 'commodity', name: '商品', score: 38, view: '中性' },
      { id: 'cash', name: '现金/货币', score: 50, view: '中性' },
    ],
    monthlyStrategy: {
      ym: todayStr.slice(0, 7),
      content: '',
    },
  }

  // ---------- 12. 主动型基金 / ETF（真实持仓 + 电网ETF观察） ----------
  const funds = [
    createFund({
      code: '159139',
      name: '159139',
      fundType: '行业主题',
      investmentStyle: '成长',
      currency: 'CNY',
      status: '已持仓',
      analysisNotes: '场内 ETF，持续跟踪净值与指数走势。',
      isSample: false,
    }),
    createFund({
      code: '159770',
      name: '159770',
      fundType: '行业主题',
      investmentStyle: '成长',
      currency: 'CNY',
      status: '已持仓',
      analysisNotes: '场内 ETF，持续跟踪净值与指数走势。',
      isSample: false,
    }),
    createFund({
      code: '159994',
      name: '159994',
      fundType: '行业主题',
      investmentStyle: '成长',
      currency: 'CNY',
      status: '已持仓',
      analysisNotes: '场内 ETF，持续跟踪净值与指数走势。',
      isSample: false,
    }),
    createFund({
      code: '512480',
      name: '512480（半导体ETF）',
      fundType: '行业主题',
      investmentStyle: '成长',
      currency: 'CNY',
      status: '已持仓',
      analysisNotes: '半导体主题 ETF，跟踪中证全指半导体指数，弹性与波动均较大。',
      relatedIsIds: ['IS-2026-002'],
      isSample: false,
    }),
    createFund({
      code: '512630',
      name: '512630',
      fundType: '行业主题',
      investmentStyle: '成长',
      currency: 'CNY',
      status: '已持仓',
      analysisNotes: '场内 ETF，持续跟踪净值与指数走势。',
      isSample: false,
    }),
    createFund({
      code: '001194',
      name: '001194',
      fundType: '主动股票型',
      investmentStyle: '成长',
      currency: 'CNY',
      status: '已持仓',
      analysisNotes: '场外主动基金，需按基金代码做穿透分析后补全基金经理与持仓。',
      isSample: false,
    }),
    createFund({
      code: '001917',
      name: '001917',
      fundType: '主动股票型',
      investmentStyle: '均衡',
      currency: 'CNY',
      status: '已持仓',
      analysisNotes: '场外主动基金，需按基金代码做穿透分析后补全基金经理与持仓。',
      isSample: false,
    }),
    createFund({
      code: '673010',
      name: '673010',
      fundType: '主动股票型',
      investmentStyle: '均衡',
      currency: 'CNY',
      status: '已持仓',
      analysisNotes: '场外主动基金，需按基金代码做穿透分析后补全基金经理与持仓。',
      isSample: false,
    }),
    createFund({
      code: '004433',
      name: '004433',
      fundType: '主动股票型',
      investmentStyle: '均衡',
      currency: 'CNY',
      status: '已持仓',
      analysisNotes: '场外主动基金，需按基金代码做穿透分析后补全基金经理与持仓。',
      isSample: false,
    }),
    createFund({
      code: '008923',
      name: '008923',
      fundType: '主动股票型',
      investmentStyle: '均衡',
      currency: 'CNY',
      status: '已持仓',
      analysisNotes: '场外主动基金，需按基金代码做穿透分析后补全基金经理与持仓。',
      isSample: false,
    }),
    createFund({
      code: '',
      name: '电网ETF（关注）',
      fundType: '行业主题',
      investmentStyle: '均衡',
      currency: 'CNY',
      status: '观察中',
      analysisNotes: '当前看好的方向：电网上中游产业链（电网建设/设备/特高压），受益于新能源并网与电网投资景气，待深入分析。',
      relatedIsIds: ['IS-2026-002', 'IS-2026-005'],
      isSample: false,
    }),
  ]

  // ---------- 13. 行业趋势观察 ----------
  // 当前看好的行业方向：电网 / 电力设备（新能源并网 + 电网投资景气）。
  const industryWatches = [
    createIndustryWatch({
      name: '电力设备与电网',
      code: 'CS0130',
      category: '二级重点',
      trend: { current: '上升趋势', direction: '看多', score: 70 },
      status: '择时入场',
      prosperity: {
        score: 4,
        revenueGrowth: 12.5,
        profitGrowth: 18.6,
        capacityUtilization: 80,
        orderVisibility: 76,
        pmiNewOrders: 52.8,
        change: '上行',
      },
      valuation: {
        pe: 26,
        pePercentile: 48,
        pb: 3.6,
        pbPercentile: 45,
        dividendYield: 1.6,
        fairValue: '22-30',
      },
      capitalFlow: {
        mainFlow: 30.5,
        northFlow: 10.2,
        etfShareChange: 7.8,
        trend: '流入',
      },
      policy: {
        supportLevel: '强支持',
        keyPolicies: [
          { name: '新型电力系统建设（特高压/配网）', date: '2026-06', impact: '强正面' },
          { name: '电网投资计划加码', date: '2026-03', impact: '正面' },
          { name: '新能源大基地并网需求', date: '2026-05', impact: '正面' },
        ],
        notes: '电网投资确定性高，特高压与配网改造带来订单景气上行',
      },
      indicators: {
        prosperityTrend: true,
        capitalFlowTrend: true,
        valuationTrend: true,
        policyTrend: true,
        confirmed: false,
      },
      triggerConditions: {
        entry: ['特高压招标放量', '电网投资额超预期', '电力设备订单持续增长'],
        exit: ['电网投资节奏放缓', '估值分位超过70%', '资金持续流出'],
      },
      relatedTargets: [
        { targetId: 'T-DW', targetName: '电网ETF', weight: 5 },
      ],
      researchNotes: [
        { date: '2026-08-25', content: '用户重点看好电网方向：新能源并网提速，电网投资确定性高，趋势与政策共振', author: 'AI' },
        { date: '2026-08-20', content: '关注电网ETF，待估值与资金信号确认后纳入仓位管理', author: 'AI' },
      ],
      allocationSuggestion: { position: 8, type: '加仓', timing: '可建仓' },
      isSample: false,
    }),
  ]

  // ---------- 示例：L3 2026-Q3 中长期策略（第十五章 §15.4.1） ----------
  const strategies = [
    createStrategy({
      ym: '2026-Q3',
      title: '2026Q3 衰退末期·防守反击策略',
      macroPhase: '衰退末期',
      macroPhaseConfidence: 65,
      macroKeyRationale: 'PMI连续两月略高于荣枯线但弱于历史均值；社融企稳；CPI低位；对应衰退末期向复苏过渡。',
      macroSignalConflicts: '地产投资仍弱，出口压力大，但内需和政策托底在起作用——信号不完全一致，判定为过渡期偏弱的衰退末期。',
      assetAllocation: {
        equityRange: { min: 55, max: 70 },
        bondRange: { min: 20, max: 30 },
        goldRange: { min: 5, max: 10 },
        cashRange: { min: 5, max: 15 },
        equityTone: '中性偏下',
      },
      industryFocus: {
        overweight: [
          { code: 'CS0130', name: '电力设备与电网', reason: '新能源并网提速 + 电网投资加码，特高压/配网景气上行' },
          { code: 'CS0301', name: '黄金', reason: '避险+降息逻辑，衰退末期标配' },
        ],
        neutral: [
          { code: 'CS0111', name: '半导体' },
          { code: 'CS0125', name: '医药生物' },
        ],
        underweight: [
          { code: 'CS02XX', name: '高估值题材', reason: '衰退末期流动性偏紧' },
        ],
      },
      styleBias: '价值侧重',
      coreAssumptions: [
        { id: 'a1', text: 'Q3 PMI不会跌破荣枯线', verified: false },
        { id: 'a2', text: '电网投资与特高压招标维持高景气', verified: false },
        { id: 'a3', text: '美联储停止加息、国内不收紧货币政策', verified: false },
      ],
      humans: { phaseJudgement: true, industryPriority: false, finalApproval: false },
      ais: {
        macroEvidence: '宏观周期Agent输出：PMI/CPI组合位于衰退末期左下象限，置信65%',
        industryEvidence: '行业景气Agent：电网/电力设备景气上行，黄金上行趋势，半导体拐点待确认',
        allocationSuggestion: '大类配置辅助建议：权益取区间中下部（55-60%），债券25%，黄金8-10%',
        conflicts: [
          { agents: '宏观周期 vs 市场情绪', point: '宏观看弱衰退末期，但情绪已反弹较多', reason: '情绪领先基本面' },
        ],
      },
      status: '执行中',
      createdAt: todayStr,
      updatedAt: todayStr,
      isSample: false,
    }),
  ]

  // ---------- L4 2026-08 月度策略（用户实际执行计划，含电网ETF观察） ----------
  const monthlyStrategies = [
    createMonthlyStrategy({
      ym: '2026-08',
      title: '8月月度·防御底仓 + 黄金小幅超配',
      strategyId: strategies[0].id,
      strategyTitle: strategies[0].title,
      keyObservations: [
        { text: 'PMI官方公布', metric: 'PMI', target: '≥49.8', actual: '待公布', passed: false },
        { text: '食品饮料中报验证', metric: '白酒板块净利润增速', target: '≥5%', actual: '待公布', passed: false },
      ],
      rebalancePlan: {
        equityChange: 0,
        bondChange: 0,
        goldChange: 2,
        cashChange: -2,
        rationale: '美国通胀回落确认，黄金加2个百分点，对应现金减少。',
      },
      industryRebalance: [
        { industryCode: 'CS0301', industryName: '黄金', action: '加仓', changePct: 2, reason: '降息预期升温' },
      ],
      targetActionPlan: [
        { targetCode: '601088', targetName: '中国神华', targetType: '个股', action: '持有', targetPositionRange: { min: 8, max: 12 }, triggers: ['跌破买入价12%止损'], relatedMemoId: '' },
        { targetCode: '', targetName: '电网ETF（关注）', targetType: '基金', action: '观察', targetPositionRange: { min: 0, max: 8 }, triggers: ['特高压招标放量/资金流入确认后建仓'], relatedMemoId: '' },
      ],
      createdAt: todayStr,
      updatedAt: todayStr,
      isSample: false,
    }),
  ]

  // ---------- L5/L6 评分卡（示例已清除，按用户实际标的生成） ----------
  const scoreCards = []

  // ---------- 基金代码穿透分析任务（示例已清除，按需输入基金代码创建） ----------
  const fundAnalysisJobs = []

  return {
    principles,
    l1,
    methods,
    targets,
    trades,
    reviews,
    observations,
    memos,
    materials,
    logs,
    funds,
    industryWatches,
    strategies,
    monthlyStrategies,
    scoreCards,
    fundAnalysisJobs,
    dashboard,
    analysis: { targets: {}, macro: null }, // 实时分析结果缓存（垂类 Agent 分析输出）
    version: 'v2.5',
  }
}
